route_path:
  ltp:
    sent_split: /sent_split
    add_words: /add_words
    cws: /cws
    pos: /pos
    ner: /ner
    srl: /srl
    dep: /dep
    sdp: /sdp
    sdpg: /sdpg
    all: /all
  sys:
    login: /login
    logout: /logout
    get_user_info: /get_user_info
    get_prem_code: /get_prem_code
    test_retry: /test_retry
    get_menu_list: /get_menu_list
default_host: "127.0.0.1"
default_port: 8000
default_max_window: 4